//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samaj_Kalyan.SamajKalayan.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralAgreement
    {
        public GeneralAgreement()
        {
            this.GA_Attachment = new HashSet<ze>();
            this.IngoRenewals = new HashSet<IngoRenewal>();
            this.IngoTerminations = new HashSet<IngoTermination>();
            this.ProjectAgreements = new HashSet<ProjectAgreement>();
        }
    
        public int GeneralAgreement_ID { get; set; }
        public string Name_Of_Ingo { get; set; }
        public string Name_of_Ingo_Nepali { get; set; }
        public string Country { get; set; }
        public string Ga_Date_Nepali { get; set; }
        public Nullable<System.DateTime> Ga_Date { get; set; }
        public string Period { get; set; }
        public Nullable<decimal> Pre_Annum_Commitment_Amount { get; set; }
        public Nullable<decimal> Ga_Service_Charge { get; set; }
        public string Sector { get; set; }
        public string Hq_Address { get; set; }
        public string Contact_Person { get; set; }
        public string Country_Official_Nepal_Address { get; set; }
        public Nullable<int> Contact_Number { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> GA_TerminationDate { get; set; }
        public string Ga_TerminationDate_Nepali { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletdedDate { get; set; }
        public string Scan_GA_Location { get; set; }
        public string PA_Attachment_Location { get; set; }
    
        public virtual ICollection<ze> GA_Attachment { get; set; }
        public virtual ICollection<IngoRenewal> IngoRenewals { get; set; }
        public virtual ICollection<IngoTermination> IngoTerminations { get; set; }
        public virtual ICollection<ProjectAgreement> ProjectAgreements { get; set; }
    }
}
