//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samaj_Kalyan.SamajKalayan.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngoTermination
    {
        public int TerminationId { get; set; }
        public Nullable<int> IngoId { get; set; }
        public string TerminationDateNp { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public string NameOfAssest { get; set; }
        public string EvaluationOfReportAttached { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DeletdDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual GeneralAgreement GeneralAgreement { get; set; }
    }
}
