//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samaj_Kalyan.SamajKalayan.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_PartnerNgo
    {
        public int PA_PatnerNGOs_ID { get; set; }
        public Nullable<int> Ngo_Number { get; set; }
        public string Ngo_Name { get; set; }
        public Nullable<int> ProjectAgreement_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual ProjectAgreement ProjectAgreement { get; set; }
    }
}
