//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samaj_Kalyan.SamajKalayan.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrincipaleConstantOfVolunter
    {
        public int VolunteerID { get; set; }
        public Nullable<int> GA_Id { get; set; }
        public Nullable<int> PA_Id { get; set; }
        public string Council_sRagistrationNumber { get; set; }
        public Nullable<System.DateTime> C_Council_sRagistrationDate { get; set; }
        public string C_Council_sRagistrationDateNp { get; set; }
        public string NameOfAppicant { get; set; }
        public string Country { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<decimal> VisaDuration { get; set; }
        public string ApplicationDesingation { get; set; }
        public string ApplicationSector { get; set; }
        public string Agreement { get; set; }
        public string ServiceReciverNGOSName { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public string DecisionDateNp { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreateedBy { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual ProjectAgreement ProjectAgreement { get; set; }
    }
}
