//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samaj_Kalyan.SamajKalayan.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAgreement_Districts
    {
        public int ProjectAgreementBudgetBreakDown_ID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<decimal> DistrictWiseAmmount { get; set; }
        public Nullable<int> ProjectAgreementID { get; set; }
        public Nullable<int> Locallevel { get; set; }
        public Nullable<int> ProvienceId { get; set; }
    
        public virtual ProjectAgreement ProjectAgreement { get; set; }
    }
}
