//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samaj_Kalyan.SamajKalayan.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class provincesVDCDetail
    {
        public int ProvincesVDCDetailsID { get; set; }
        public string VDCName { get; set; }
        public int ProvincesId { get; set; }
        public int ProvincesDistrictId { get; set; }
        public int VdcOrMunicipilityTypeId { get; set; }
        public int Status { get; set; }
    }
}
