//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samaj_Kalyan.SamajKalayan.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SamajkalyanEntities : DbContext
    {
        public SamajkalyanEntities()
            : base("name=SamajkalyanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ze> zes { get; set; }
        public virtual DbSet<GeneralAgreement> GeneralAgreements { get; set; }
        public virtual DbSet<PA_PartnerNgo> PA_PartnerNgo { get; set; }
        public virtual DbSet<PA_Sector> PA_Sector { get; set; }
        public virtual DbSet<PA_Years> PA_Years { get; set; }
        public virtual DbSet<ProjectAgreement_Districts> ProjectAgreement_Districts { get; set; }
        public virtual DbSet<ProvincesDistrictSetup> ProvincesDistrictSetups { get; set; }
        public virtual DbSet<ProvincesMunType> ProvincesMunTypes { get; set; }
        public virtual DbSet<provincesSetup> provincesSetups { get; set; }
        public virtual DbSet<provincesVDCDetail> provincesVDCDetails { get; set; }
        public virtual DbSet<IngoRenewal> IngoRenewals { get; set; }
        public virtual DbSet<IngoTermination> IngoTerminations { get; set; }
        public virtual DbSet<ProjectAgreement> ProjectAgreements { get; set; }
        public virtual DbSet<IngoRewnewalDocument> IngoRewnewalDocuments { get; set; }
        public virtual DbSet<WorkPermit> WorkPermits { get; set; }
        public virtual DbSet<WorKPermitType> WorKPermitTypes { get; set; }
        public virtual DbSet<WpaFamily> WpaFamilies { get; set; }
        public virtual DbSet<PrincipaleConstantOfVolunter> PrincipaleConstantOfVolunters { get; set; }
        public virtual DbSet<HandOver_TakeOver> HandOver_TakeOver { get; set; }
        public virtual DbSet<Import_DutyFreeRecommendation> Import_DutyFreeRecommendation { get; set; }
        public virtual DbSet<VehicleAuction> VehicleAuctions { get; set; }
    }
}
