//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samaj_Kalyan.SamajKalayan.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkPermit
    {
        public WorkPermit()
        {
            this.WpaFamilies = new HashSet<WpaFamily>();
        }
    
        public int WorkPermitId { get; set; }
        public Nullable<int> WorkPermitTypeId { get; set; }
        public Nullable<int> PA_Id { get; set; }
        public Nullable<int> GA_Id { get; set; }
        public Nullable<int> Council_sRegistrationNumber { get; set; }
        public Nullable<System.DateTime> CouncilRegistrationDate { get; set; }
        public string CouncilRegistrationDateNp { get; set; }
        public string NameOfApplicant { get; set; }
        public string Country { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<decimal> VisaDuration { get; set; }
        public string ApplicationDesingation { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public string DecisionDateNp { get; set; }
        public string VisaType { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<int> UpDatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ProjectAgreement ProjectAgreement { get; set; }
        public virtual WorKPermitType WorKPermitType { get; set; }
        public virtual ICollection<WpaFamily> WpaFamilies { get; set; }
    }
}
