//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samaj_Kalyan.SamajKalayan.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ze
    {
        public int GA_Attachment_ID { get; set; }
        public string Scan_GA_Location { get; set; }
        public string PA_Attachment_Location { get; set; }
        public Nullable<int> GeneralAgreement_ID { get; set; }
    
        public virtual GeneralAgreement GeneralAgreement { get; set; }
    }
}
